parameters:
  - name: buildConfiguration
    default: 'Release'
  - name: buildPlatform
    default: 'Any CPU'
  - name: projectName
    default: ' '
  - name: stage
    default: 'BuildModel'
  - name: vmImage
    default: 'windows-latest'

jobs:
- job: ${{ parameters.stage }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
    - task: NuGetToolInstaller@1

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(Build.ArtifactStagingDirectory)

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    
    - task: VSBuild@1
      displayName: CodeAnalysis
      inputs:
        solution: '${{parameters.projectName}}'
        msbuildArgs: '/p:RunCodeAnalysis=true'
        platform: '${{parameters.buildPlatform}}'
        configuration: '${{parameters.buildConfiguration}}'

    - task: VSBuild@1
      displayName: CodeMetrics
      inputs:
        solution: '${{parameters.projectName}}'
        msbuildArgs: '/t:Metrics /p:MetricsOutputFile=$(Build.ArtifactStagingDirectory)/${{parameters.projectName}}.Metrics.xml'
        platform: '${{parameters.buildPlatform}}'
        configuration: '${{parameters.buildConfiguration}}'

    - task: VSBuild@1
      inputs:
        solution: '${{parameters.projectName}}'
        platform: '${{parameters.buildPlatform}}'
        configuration: '${{parameters.buildConfiguration}}'

    - task: CopyFiles@2
      inputs:
        Contents: '**\bin\**'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '12f53bf0-b08a-4c7b-a8de-1ce933bf0eab/b51b6377-6b9c-4152-9a9c-c85d546b8403'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'model dll drop'
      condition: succeeded()